{
 "title": "Notes API — alamin",
 "tags": [
  "exam",
  "alamin"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "App scrape UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"notes-api\"}",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Requests in flight (ekhon)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "http_requests_in_flight", "legendFormat": "in flight" }
   ]
  },
  {
   "title": "Scrape duration (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"notes-api\"}",
     "legendFormat": "scrape"
    }
   ]
  },
  {
   "title": "Request rate (req/s) by route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "p95 latency by route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "DB queries per request (N+1 ekhane dekha jay)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(db_queries_per_request_sum[5m]) / rate(db_queries_per_request_count[5m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "DB query rate by query_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(db_query_duration_seconds_count[5m])) by (query_name)",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "p95 DB query time by query_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_query_duration_seconds_bucket[5m])) by (le, query_name))",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "5xx rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}