global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'notes-api'
    static_configs:
      - targets: ['app:3000']    # compose network e service naam diyei jawa jay

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
